#pragma once

#define EE_HANDS
#define ENCODER_RESOLUTION 2

#ifdef RGBLIGHT_ENABLE
  #define RGBLIGHT_SLEEP
  #define RGBLIGHT_LIMIT_VAL 200
  #define RGBLIGHT_HUE_STEP 8
  #define RGBLIGHT_SAT_STEP 8
  #define RGBLIGHT_VAL_STEP 8

  // Animation
  #define RGBLIGHT_EFFECT_BREATHING
  #define RGBLIGHT_DEFAULT_MODE RGBLIGHT_MODE_BREATHING
  #define RGBLIGHT_DEFAULT_HUE 112
  #define RGBLIGHT_EFFECT_BREATHE_CENTER 1.85
  #define RGBLIGHT_EFFECT_BREATHE_MAX RGBLIGHT_LIMIT_VAL

  // Layers
  // #define RGBLIGHT_LAYERS
#endif

#define IGNORE_MOD_TAP_INTERRUPT
#define TAPPING_FORCE_HOLD
